name: techstagram
description: A new Social Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version numbe1.2.0r is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: null
  cached_network_image: null
  camera: ^0.8.1+2
  catcher: null
  cloud_firestore: ^2.2.0
  cupertino_icons: null
  double_back_to_close_app: null
  firebase_auth: ^1.2.0
  firebase_core: null
  firebase_database: null
  firebase_messaging: null
  firebase_storage: ^8.1.3
  flutter_facebook_login: null
  flutter_icons: null
  flutter_image_compress: ^1.0.0
  flutter_screenutil: null
  flutter_svg: ^0.22.0
  font_awesome_flutter: null
  google_sign_in: null
  http: null
  image: null
  image_cropper: null
  image_editor_pro: null
  image_gallery: null
  image_picker: ^0.7.5
  local_auth: null
  path: null
  path_provider: ^2.0.2
  permission_handler: null
  rename: null
  responsive_layout_builder: null
  rflutter_alert: ^2.0.2
  rxdart: null
  settings_ui: null
  shared_preferences: null
  storage_path: null
  story_view: ^0.13.1
  string_validator: null
  transparent_image: null
  video_player: null


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec 
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Cookie-Regular
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/
    - assets/images/
    - assets/icons/
