name: techstagram
description: A new Social Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version numbe1.2.0r is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  google_sign_in:
  firebase_auth:
  firebase_database:
  rename:
  cloud_firestore:
  rxdart: 0.20.0
  image_picker:
  file_picker:
  after_layout:
  firebase_storage:
  font_awesome_flutter:
  shared_preferences:
  cached_network_image: ^2.0.0-rc
  image:
  flutter_facebook_login:
  flutter_svg: 0.18.0
  camera: ^0.5.8+5
  path_provider:
  path:
  image_cropper:
  responsive_framework:
  responsive_layout_builder:
  esys_flutter_share: ^1.0.2
  video_player: ^0.10.2+5
  firebase_core: ^0.4.0+9
  provider: ^4.0.5
  firebase_messaging:
  settings_ui:
  flutter_icons: ^1.0.0+1
  ext_storage:
  timeago: ^2.0.27
  fluttertoast:
  local_auth:
  http:
  string_validator: ^0.1.4
  image_editor_pro: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Cookie-Regular
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/fb-logo.png
    - assets/fonts/
    - assets/google_icon.jpg
    - assets/icons/
    - assets/images/
    - assets/no_image.png
    - assets/phone-icon.png
    - assets/twitter-logo.png
    - assets/twitter_logo.png
    - assets/images/coverPhoto.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
