name: techstagram
description: A new Social Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version numbe1.2.0r is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  swipedetector:
  flutter_screenutil:
  line_awesome_flutter:
  google_sign_in:
  firebase_auth:
  firebase_database:
  rename:
  cloud_firestore:
  rxdart: 0.20.0
  image_picker:
  file_picker:
  after_layout:
  firebase_storage:
  location:
  geocoder:
  font_awesome_flutter:
  shared_preferences:
  cached_network_image: ^2.0.0-rc
  image:
  google_fonts:
  flutter_webview_plugin:
  flutter_facebook_login:
  flutter_svg: 0.18.0
  twitter_login:
  camera: ^0.7.0
  path_provider:
  path:
  image_cropper:
  velocity_x:
  oauth1:
  adv_camera: ^1.1.3+1
  firebase_core_web:
  location_web:
  cloud_firestore_web:
  firebase_auth_web:
  responsive_framework:
  responsive_layout_builder:
  esys_flutter_share: ^1.0.2
  video_player: ^0.10.2+5
#  thumbnails: 1.0.1
  torch_compat: ^1.0.2
#  lamp: ^0.0.6
  firebase_core: ^0.4.0+9
  provider: ^4.0.5
  holding_gesture: ^0.0.3
  firebase_messaging:
  settings_ui:
  fluro:
  flutter_icons: ^1.0.0+1
  sliding_up_panel:
  ext_storage:
  permission_handler:
  timeago: ^2.0.27
  catcher:
  local_auth:
  http:
  string_validator: ^0.1.4
  image_editor_pro: ^1.0.6

  animated_icon_button:
  storage_path: ^0.2.0
  transparent_image: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Cookie-Regular
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/fb-logo.png
    - assets/fonts/Barlow-Bold.ttf
    - assets/fonts/Barlow-Regular.ttf
    - assets/fonts/Barlow-SemiBold.ttf
    - assets/fonts/Cookie-Regular.ttf
    - assets/fonts/Pacifico-Regular.ttf
    - assets/fonts/Quicksand-Bold.ttf
    - assets/fonts/Quicksand-Medium.ttf
    - assets/fonts/Quicksand-Regular.ttf
    - assets/fonts/Quicksand-SemiBold.ttf
    - assets/google_icon.jpg
    - assets/icons/chat.svg
    - assets/icons/facebook.svg
    - assets/icons/google-icon.svg
    - assets/icons/google-plus.svg
    - assets/icons/instagram.svg
    - assets/icons/login.svg
    - assets/icons/signup.svg
    - assets/icons/twitter.svg
    - assets/images/1.jpg
    - assets/images/loading.gif
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/empty.png
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/main_top.png
    - assets/images/my_profile.jpg
    - assets/images/photo4.jpg
    - assets/images/photo5.jpg
    - assets/images/gogo.png
    - assets/images/nocover.png
    - assets/images/placeholder.jpg
    - assets/images/post2.jpg
    - assets/images/signup_top.png
    - assets/images/loading.gif
    - assets/no_image.png
    - assets/phone-icon.png
    - assets/twitter-logo.png
    - assets/twitter_logo.png
    - assets/images/coverPhoto.jpg
    - assets/25.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
